---

- hosts: all
  become: true
  tasks:

  - name: update debian repository index
    apt:
      update_cache: yes
    when: ansible_distribution in ["Debian", "Ubuntu"]
  
  - name: update redhat repository index
    dnf:
       name: "*"
       state: latest
    when: ansible_distribution == "RedHat"

  - name: Install apache2 and php package
    apt:
       name: 
         - apache2
         - libapache2-mod-php
       state: latest
    when: ansible_distribution == "Ubuntu"

  - name: Install httpd and php package
    dnf:
       name: 
         - httpd
         - php
       state: latest
    when: ansible_distribution == "RedHat"


