---

- hosts: all
  become: true
  tasks:


  - name: Remove apache packege
    apt:
      name: apache2
      state: absent

  - name: Remove php support for apache2
    apt:
      name: libapache2-mod-php
      state: absent
