---

- hosts: all
  become: true
  tasks:

  - name: install updates (RedHat)
    dnf:
      update_only: yes
      update_cache: yes
    when: ansible_distribution == "RedHat"

  - name: install updates (Ubuntu)
    apt:
      upgrade: dist
      update_cache: yes
    when: ansible_distribution == "Ubuntu"
  
  - name: Create file
    file:
      path: /opt/my_new_file.txt
      state: touch

  - name: Edit created file
    copy:
      dest: "/opt/my_new_file.txt"
      content: |
        line 01
        line 02
        line 03

  - name: Edit hosts file
    copy:
      dest: "/etc/hosts"
      content: |
        192.168.20.21   ansible
        192.168.20.22   wazuh
        192.168.20.23   rhel08
        192.168.20.24   ubu20

  - name: Create a new directory
    file:
      path: "/tarzan"
      state: absent 

  - name: Ensure SELinux is set to disabled  mode
    ansible.builtin.lineinfile:
      path: /etc/selinux/config
      regexp: '^SELINUX='
      line: SELINUX=disabled
    when: ansible_distribution == "RedHat"

- hosts: web_servers
  become: true
  tasks:

  - name: Install apache and php for Ubuntu  servers
    apt:
      name:
        - apache2
        - libapache2-mod-php
      state: latest
      update_cache: yes
    when: ansible_distribution == "Ubuntu"

  - name: Install httpd and php for RedHat servers
    dnf:
      name:
        - httpd
        - php
      state: latest
    when: ansible_distribution == "RedHat"

- hosts: db_servers
  become: true
  tasks:

  - name: Install mariadb on Ubuntu
    apt:
      name:
        - mariadb-server
      state: latest
    when: ansible_distribution == "Ubuntu"

- hosts: file_servers
  become: true
  tasks:

  - name: Install vsftpd on Ubuntu
    apt:
      name:
        - vsftpd
      state: latest
    when: ansible_distribution == "Ubuntu"


